controller:
  admin:
    username: admin
    password: admin
  serviceType: NodePort
  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code
    - matrix-auth
    - job-dsl
    - docker-workflow
    - kubernetes-cli
    - prometheus
    - blueocean
  persistence:
    enabled: true
    size: 4Gi
    storageClass: standard

  JCasC:
    defaultConfig: false
    configScripts:
      credentials: |
        credentials:
          system:
            domainCredentials:
              - credentials:
                  - string:
                      scope: GLOBAL
                      id: "SMTP_EMAIL"
                      description: "SMTP email"
                      secret: {{ .Values.mySecrets.smtpEmail | quote }}
                  - string:
                      scope: GLOBAL
                      id: "SMTP_PASS"
                      description: "SMTP password"
                      secret: {{ .Values.mySecrets.smtpPass | quote }}
                  - string:
                      scope: GLOBAL
                      id: "GRAFANA_ADMIN_PASS"
                      description: "Grafana admin password"
                      secret: {{ .Values.mySecrets.grafanaAdminPass | quote }}
      my-config: |-
        jobs:
          - script: >
              pipelineJob('deploy-monitoring') {
                definition {
                  cpsScm {
                    scm {
                      git {
                        remote {
                          url('https://github.com/stringersix/rsschool-devops-course-tasks')
                        }
                        branches('task_7')
                      }
                    }
                    scriptPath('jenkins/Jenkinsfile')
                  }
                }
              }