controller:
  admin:
    username: admin
    password: admin666
  serviceType: NodePort
  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code
    - matrix-auth
    - job-dsl
  persistence:
    enabled: true
    size: 4Gi
    storageClass: standard
  JCasC:
    configScripts:
      hello-job: |
        jobs:
          - script: >
              job('hello-world') {
                steps {
                  shell('echo Hello world')
                }
              }
      security: |
        jenkins:
          securityRealm:
            local:
              allowsSignup: false
              users:
                - id: "user1"
                  password: "password1"
                - id: "user2"
                  password: "password2"
          authorizationStrategy:
            loggedInUsersCanDoAnything:
              allowAnonymousRead: false
